In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

## nombres

In [2]:
# carga de dataset
digitos = datasets.load_digits()
X = digitos['data']
t = digitos['target']

1- Analice la información que se encuentra en $X$ y $t$. ¿Qué debemos realizar, una regresión o una clasificación? Cómo se podría ajustar a una clasificación o a una regresión, argumente.

In [7]:
print(X,X.shape)
print(t)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]] (1797, 64)
[0 1 2 ... 8 9 8]


2- Desarrolle una función que simule el $holdout$ $method$. El porcentaje de $X$ que se va a usar para entrenar debe estar parametrizado. No debe usar niguna dependecia a parte de numpy.

In [9]:
def holdoutMethod (X,porcentajeE=0.2):
    size=int(len(X)*porcentajeE)
    return X[:size,:], X[size:,:]

X1,X2=holdoutMethod(X)
print(X1,X1.shape)
print(X2,X2.shape)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  2. ...  0.  0.  0.]
 [ 0.  0.  3. ...  8.  0.  0.]
 [ 0.  0.  5. ...  1.  0.  0.]] (359, 64)
[[ 0.  0.  6. ... 11.  1.  0.]
 [ 0.  0.  1. ... 11.  2.  0.]
 [ 0.  0.  3. ...  0.  0.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]] (1438, 64)


3- Usando la función desarrollada en el punto 2, divida los datos con el 70% para entrenar y el 30% para prueba. Use la dependencia de RNA para clasificar, entrenar y predecir usando tanto el conjunto de entrenamiento como el de pruebas. Use como solver sgd y como función de activación la función logística.
Usando accuracy_score determine la exactitud para t de entrenamiento y t de pruebas <a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html">Ver</a>.

¿Qué resultados obtuvo, intérprete?

In [13]:
X1,X2=holdoutMethod(X,porcentajeE=0.7)
print(X1,X1.shape)
print(X2,X2.shape)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  0. ...  3.  0.  0.]
 [ 0.  0.  5. ... 11.  3.  0.]
 [ 0.  0.  3. ...  0.  0.  0.]] (1257, 64)
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  5. ...  3.  0.  0.]
 [ 0.  7. 16. ...  0.  0.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]] (540, 64)


4- Siga los siguientes pasos:
* Use Normalizer para normalizar el conjunto de entrenamiento <a href="https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html">Ver</a>.
* Use train_test_split para armar el conjunto de entrenamiento y el conjunto de pruebas. Use 70% para entrenar y 30% para pruebas <a href="https://scikit-learn.org/stable/modules/cross_validation.html#">Ver</a>.
* Use una red neuronal con parámetros que desee, para generar un buen modelo <a href="https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html">Ver</a>.
* Prediga los resultados para t de entrenamiento y t de pruebas. Usando accuracy_score determine la exactitud para t de entrenamiento y t de pruebas <a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html">Ver</a>. 
* ¿Qué resultados obtuvo? Interprete.

5- Ahora usando cross_val_score con un cv = 7 (<a href="https://scikit-learn.org/stable/modules/cross_validation.html#computing-cross-validated-metrics">Ver</a>), ajuste un buen modelo ¿Qué resultados obtuvo? Interprete.